[package]
name = "fantasy-name-generator"
version = "0.2.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["json"] }  
serde = { version = "1.0.213", features = ["derive"] }  
tokio = { version = "1.41.0", features = ["full"] }  
serde_json = "1.0"
dotenv = "0.15"